spring.application.name=SpringMvc

#data source DB연결
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=oraclejava

#ddl_auto
#   create : SessionFactory; //시작시 스키마를 삭제하고 재생성
#   create-drop : SessionFactory; //종료시에 스키마를 삭제함
#   update : SessionFactory
#   validate : SessionFactory //접속스키마와 다를 경우 예외처리
#   none : 아무것도 안함 //서비스가 돌고 있을 경우
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.column_ordering_strategy=legacy
spring.jpa.show-sql=true